repos:
- repo: local
  hooks:
  - id: sqflint
    name: SQF syntax check
    entry: ./scripts/sqflint-hook.sh
    language: script
    files: \.sqf$
    exclude: ^addons/Viceroys-STALKER-ALife/functions/core/fn_traceFunction\.sqf$
